// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var WorkerD, worker_util;
    worker_util = require('./worker_util');
    return WorkerD = (function() {
      var dfr, o, onMessage;

      dfr = $.Deferred();

      o = $({});

      onMessage = function(event) {
        var data;
        data = event.data;
        if (typeof data === 'object' && (data.msgId != null)) {
          return o.trigger(data.msgId, [data[data.msgId], event]);
        }
      };

      function WorkerD(inlineWorker_js, opts) {
        this.worker = worker_util.createInlineWorker(inlineWorker_js);
        this.worker.addEventListener('message', onMessage);
      }

      WorkerD.prototype.send = function() {
        return this.worker.postMessage.apply(this.worker, arguments);
      };

      WorkerD.prototype.on = function(id, handle) {
        return o.on.apply(o, arguments);
      };

      return WorkerD;

    })();
  });

}).call(this);
