// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require) {
    var WorkerD, worker_util;

    worker_util = require('./worker_util');
    return WorkerD = (function() {
      var dfr, o, onMessage;

      dfr = $.Deferred();

      o = $({});

      onMessage = function(event) {
        var data;

        data = event.data;
        if (typeof data === 'object' && (data.msgId != null)) {
          return o.trigger(data.msgId, [data[data.msgId], event]);
        }
      };

      function WorkerD(inlineWorker_js, opts) {
        this.worker = worker_util.createInlineWorker(inlineWorker_js);
        this.worker.addEventListener('message', onMessage);
      }

      WorkerD.prototype.send = function(id, msgData, options) {
        var msg;

        msg = {
          msgId: id,
          msgData: msgData
        };
        return this.worker.postMessage.apply(this.worker, [msg, options]);
      };

      WorkerD.prototype.on = function(id, handle) {
        return o.on.apply(o, arguments);
      };

      WorkerD.prototype.terminate = function() {
        return this.worker.terminate();
      };

      return WorkerD;

    })();
  });

}).call(this);
