// Generated by CoffeeScript 1.3.3
(function() {

  this.send = function(id, data) {
    var res;
    res = {};
    res.msgId = id;
    res[id] = data;
    return self.postMessage(res);
  };

}).call(this);
