// Generated by CoffeeScript 1.6.2
(function() {
  var attr, console_attr, _i, _len,
    _this = this;

  this.postDebugMessage = function(type, args) {
    return postMessage({
      debug: type,
      args: args
    });
  };

  console_attr = ['debug', 'error', 'info', 'log', 'warn', 'dir', 'dirxml', 'trace', 'assert', 'count', 'markTimeline', 'profile', 'profileEnd', 'time', 'timeEnd', 'timeStamp', 'group', 'groupCollapsed', 'groupEnd'];

  this.console = {};

  for (_i = 0, _len = console_attr.length; _i < _len; _i++) {
    attr = console_attr[_i];
    this.console[attr] = (function(attr) {
      return function() {
        return _this.postDebugMessage(attr, arguments);
      };
    })(attr);
  }

}).call(this);
