// Generated by CoffeeScript 1.3.3
(function() {

  console.log('inlineWorker loaded');

  this.on("getSum", function(max) {
    var cnt, sum;
    sum = cnt = 0;
    while (cnt <= max) {
      sum += cnt++;
    }
    self.send('getSum', sum);
    return console.log('inlineWorker send message');
  });

}).call(this);
