// Generated by CoffeeScript 1.3.3
(function() {

  console.log('inlineWorker loaded');

  self.addEventListener("message", function(e) {
    var cnt, max, sum;
    console.log('inlineWorker got message');
    sum = cnt = 0;
    max = 1000000000;
    while (cnt <= max) {
      sum += cnt++;
    }
    self.send('getSum', sum);
    return console.log('inlineWorker send message');
  });

}).call(this);
