
// Generated by CoffeeScript 1.6.2
(function() {
  define('test-car',['require'],function(require) {
    var Car;

    return Car = (function() {
      function Car(color) {
        this.color = color;
      }

      Car.prototype.get = function(attr) {
        if (this[attr]) {
          return this[attr];
        }
      };

      return Car;

    })();
  });

}).call(this);

// Generated by CoffeeScript 1.6.2
(function() {
  console.log('inlineWorker loaded');

  require(["require", "module", "test-car"], function(require, module, Car) {
    var car;

    car = new Car('red');
    return console.log(car);
  });

  this.on("getSum", function(max) {
    var cnt, sum;

    console.time('getSum');
    console.log('getSum', max);
    sum = cnt = 0;
    while (cnt <= max) {
      sum += cnt++;
    }
    console.log('sum=', sum);
    self.send('getSum', sum);
    console.log('inlineWorker send message');
    return console.timeEnd('getSum');
  });

}).call(this);

define("inlineWorker", function(){});
