// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var ChatRoom, sharedworker_js, worker_util;
    sharedworker_js = require('text!./sharedWorker.js');
    worker_util = require('./lib/worker/worker_util');
    ChatRoom = (function() {

      function ChatRoom() {
        this.worker = worker_util.createInlineSharedWorker(sharedworker_js, 'chatroom');
        this.worker.port.addEventListener('message', this.onMessage, false);
        console.log(this.worker);
        console.log('initial ChatRoom');
        this.worker.port.start();
      }

      ChatRoom.prototype.onMessage = function(event) {
        var data;
        console.log(event);
        data = event.data;
        return console.log(data);
      };

      return ChatRoom;

    })();
    return new ChatRoom();
  });

}).call(this);
