// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require) {
    var worker_console_spec_js, worker_util;

    worker_console_spec_js = require('text!./worker_console_spec.js');
    worker_util = require('./lib/worker/worker_util');
    console.log(worker_util);
    buster.spec.expose();
    return describe("worker console", function() {
      var inlineworker;

      inlineworker = worker_util.createInlineWorker(worker_console_spec_js);
      if (worker_util.options.enableDebug) {
        return it('should print out log from worker', function() {
          return expect(true).toBeTrue();
        });
      } else {
        return it("shouldn't print out log from worker", function() {
          return expect(true).toBeTrue();
        });
      }
    });
  });

}).call(this);
