// Generated by CoffeeScript 1.3.3
(function() {
  var connections;

  connections = 0;

  self.addEventListener("connect", (function(e) {
    var port;
    port = e.ports[0];
    port.addEventListener("message", (function(e) {
      return port.postMessage("Welcome to " + e.data + " (On port #" + connections + ")");
    }), false);
    connections++;
    return port.postMessage("connection ok:" + connections);
  }), false);

}).call(this);
