// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require) {
    var Car;

    return Car = (function() {
      function Car(color) {
        this.color = color;
      }

      Car.prototype.get = function(attr) {
        if (this[attr]) {
          return this[attr];
        }
      };

      return Car;

    })();
  });

}).call(this);
