// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Car;
    return Car = (function() {

      function Car(color) {
        this.color = color;
      }

      Car.prototype.get = function(attr) {
        if (this[attr]) {
          return this[attr];
        }
      };

      return Car;

    })();
  });

}).call(this);
